  
language: node_js
node_js:
  - 12
cache:
  npm: true
  directories:
    - ~/.cache  
script:
  - eslint 'src/**'
  - yarn test:coveralls
deploy:
  provider: heroku
  api_key: $HEROKU_API
  app: ts-node-api-boilerplate
  skip_cleanup: true 
notifications:
  email: false   